---
# file: roles/atlassian-proxy/handlers/main.yml

# Restart Apache
- name: restart apache
  service: name=apache2 state=restarted
  
# Reload Apache
- name: reload apache
  service: name=apache2 state=reloaded