---
# file: roles/sonarqube-server/handlers/main.yml

# Restart SonarQube
- name: restart sonarqube service
  service: name=sonarqube state=restarted
  
# Reload Apache
- name: reload apache
  service: name=apache2 state=reloaded