## Setup the ability to run a database for the Atlassian Tools
---
# file: roles/atlassian-database/tasks/main.yml

 - name: Add Percona Apt Key
   apt_key: keyserver=keys.gnupg.net id=1C4CBDCDCD2EFD2A

 - name: Add Percona Main Repository
   apt_repository: repo='deb http://repo.percona.com/apt {{ ansible_distribution_release }} main' state=present
   
 - name: Add Percona Source Repository
   apt_repository: repo='deb-src http://repo.percona.com/apt {{ ansible_distribution_release }} main' state=present 
   
 - name: Install Percona Database Server
   apt: pkg={{ item }} state=latest update_cache=yes
   with_items:
      - percona-server-server-5.6
      - percona-server-client-5.6
      
 - name: install MySQL Configuration
   template: src=atlassian-mysql.cnf.j2 dest=/etc/mysql/conf.d/atlassian-mysql.cnf
   notify: restart percona database
   
 - name: set ansible user for %
   mysql_user: name={{ mysql_root_user }} password={{ mysql_root_password }} host=% priv=*.*:ALL,GRANT state=present
   
 - name: set ansible user for localhost
   mysql_user: name={{ mysql_root_user }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT state=present
